"""init tables

Revision ID: 1fb25cad3119
Revises: 5c3f073f86f4
Create Date: 2025-05-19 00:28:50.801564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb25cad3119'
down_revision = '5c3f073f86f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор пользователя'),
    sa.Column('email', sa.String(), nullable=False, comment='Email адрес'),
    sa.Column('name', sa.String(), nullable=False, comment='Имя пользователя'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='Зашифрованный пароль'),
    sa.Column('is_company', sa.Boolean(), nullable=False, comment='Флаг компании'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Время создания записи'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор вакансии'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Название вакансии'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание вакансии'),
    sa.Column('salary_from', sa.Numeric(), nullable=True, comment='Минимальная зарплата'),
    sa.Column('salary_to', sa.Numeric(), nullable=True, comment='Максимальная зарплата'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Актуальность вакансии'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор отклика'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('job_id', sa.Integer(), nullable=False, comment='Идентификатор вакансии'),
    sa.Column('message', sa.Text(), nullable=True, comment='Сопроводительное письмо'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('jobs')
    op.drop_table('users')
    # ### end Alembic commands ###
